name: fluske
description: A Video Streaming Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+3

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

 
  animated_text_kit: ^4.2.3
  audioplayers: ^6.2.0
  # facebook_audience_network: ^1.0.1
  facebook_audience_network:
    git:
      url: https://github.com/dvlprtoastguyz/facebook_audience_network
      ###ref: ffd342ef628c34076fc66175cea5b2d25e3e8087
      ref: master
  flutter_facebook_auth: ^6.0.4
  

 
  chewie: ^1.7.4
  video_player: ^2.8.2
  subtitle_wrapper_package: ^2.1.1
  
  # payhere_mobilesdk_flutter: ^3.0.4
  file_picker: ^5.2.2
  flutter_localization: ^0.1.12
  flutter_translate: ^4.0.3
  loading_overlay: ^0.3.0
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  http: ^1.3.0
  path_provider: ^2.1.4
  sticky_headers: ^0.3.0+2
#  fluttertoast: ^8.1.1.
  fluttertoast: ^8.2.1

  # Old Version but do not upgrade it.
  intro_slider: ^3.0.10

  image_picker: ^0.8.6
  cached_network_image: ^3.4.1
  sqflite: ^2.4.1
  syncfusion_flutter_pdfviewer: ^27.1.50
  
  flutter_cache_manager: ^3.4.1
  flutter_secure_storage: ^9.2.4
  carousel_slider: ^5.0.0
 
  
  
  share_plus: ^7.0.2
  launch_review: ^3.0.1
  page_transition: ^2.0.9

  # Old Version but do not upgrade it.
  flutter_downloader: ^1.12.0

  
  
  
  permission_handler: ^10.2.0
 
  font_awesome_flutter: ^10.1.1
  bubble_tab_indicator: ^0.1.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  in_app_update: ^4.2.3
  dio: ^5.7.0
  flutter_rating_bar: ^4.0.1
  connectivity_plus: ^3.0.2
  connectivity_plus_web: ^1.2.5
  intl: ^0.18.0

  # Old Versions but do not upgrade these.
  flutter_widget_from_html: ^0.8.5
  just_audio: ^0.9.29

  firebase_messaging: ^15.1.3
  http_auth: ^1.0.1
  firebase_analytics: ^11.3.3
  flutter_lwa: ^2.0.0
  horizontal_data_table: ^4.1.2+2
  flutter_inappwebview: ^6.0.0
  # android_path_provider: ^0.3.0
  device_info_plus: ^10.1.0
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  collection: ^1.16.0
  fwfh_text_style: ^2.23.8
  wakelock_plus: ^1.1.4
  pinput: ^5.0.0
 # phonepe_payment_sdk: ^2.0.3
  get_it: ^8.0.0
  flutter_multi_formatter: ^2.13.0
  path_provider_android: ^2.2.11
  google_mobile_ads: ^2.4.0
  onesignal_flutter: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.7

dependency_overrides:
  intl: ^0.18.0
  webview_flutter: ^2.7.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/
    - icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
