// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfoJkxyCLgYMTVWk6xShUnWf8tF5Excm8',
    appId: '1:734804961771:web:55a0166ea618c1fc7b51ae',
    messagingSenderId: '734804961771',
    projectId: 'bibilto',
    authDomain: 'bibilto.firebaseapp.com',
    storageBucket: 'bibilto.firebasestorage.app',
    measurementId: 'G-3SZZJBSEW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV3bK5R8LLXuNGOjWtDSpGWGSsrIofJF4',
    appId: '1:734804961771:android:3eb65addc4744fa07b51ae',
    messagingSenderId: '734804961771',
    projectId: 'bibilto',
    storageBucket: 'bibilto.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfoJkxyCLgYMTVWk6xShUnWf8tF5Excm8',
    appId: '1:734804961771:web:51560107e7110f0e7b51ae',
    messagingSenderId: '734804961771',
    projectId: 'bibilto',
    authDomain: 'bibilto.firebaseapp.com',
    storageBucket: 'bibilto.firebasestorage.app',
    measurementId: 'G-TFBLKC7XS7',
  );
}
